-- Seed D1 Parrainly — GENERE par scripts/gen-seed-sql.mjs (ne pas editer a la main).
-- Source : data/base-parrainage.json. Idempotent (ON CONFLICT DO UPDATE).
-- Applique via : npm run d1:seed:local | d1:seed:remote
PRAGMA foreign_keys = ON;

INSERT INTO parrain (id, nom, email, statut, created_at) VALUES
  ('PAR-EMMANUEL', 'Emmanuel', 'emmanuel@parrainly.test', 'actif', (unixepoch() * 1000)),
  ('PAR-THOMAS', 'Thomas', 'thomas@parrainly.test', 'actif', (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET nom=excluded.nom, email=excluded.email;

-- REF-001 Trade Republic (actif)
INSERT INTO offre (id, nom_programme, categorie, sous_categorie, cible, pays, langue, url_parrainage, code_parrainage, description_courte, avantage_filleul, avantage_parrain, conditions, statut, priorite_affichage, tags_mcp, date_ajout, date_verification, source, notes, divulgation_affiliation, mention_risque, mention_non_affiliation, created_at, updated_at) VALUES ('REF-001', 'Trade Republic', 'Finance personnelle', 'Néobanque & Courtage', 'Jeune actif; Entrepreneur', 'FR / EU', 'fr', 'https://ref.trade.re/1dw9h6jf', '1dw9h6jf', 'Néobanque et courtier en ligne : compte rémunéré, actions, ETF, plans d''investissement programmés.', '3% d''intérêts pendant 3 mois sur le compte courant', '3% d''intérêts pendant 3 mois sur le compte courant', 'Verser 100 EUR dans les 21 premiers jours et effectuer 3 investissements.', 'actif', 1, 'banque; courtage; ETF; épargne; compte rémunéré; PEA alternatif', '2026-07-15', '2026-07-15', 'Linktree EmelGoez — extraction 15/07/2026', NULL, 'Lien de parrainage Trade Republic : Parrainly perçoit un avantage personnel (Thomas ou Emmanuel) si vous l''utilisez pour vous inscrire.', 'Investir comporte des risques de perte en capital.', 'Parrainly n''est pas affilié officiellement à Trade Republic.', (unixepoch() * 1000), (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET nom_programme=excluded.nom_programme, categorie=excluded.categorie, sous_categorie=excluded.sous_categorie, cible=excluded.cible, pays=excluded.pays, langue=excluded.langue, url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage, description_courte=excluded.description_courte, avantage_filleul=excluded.avantage_filleul, avantage_parrain=excluded.avantage_parrain, conditions=excluded.conditions, statut=excluded.statut, priorite_affichage=excluded.priorite_affichage, tags_mcp=excluded.tags_mcp, date_ajout=excluded.date_ajout, date_verification=excluded.date_verification, source=excluded.source, notes=excluded.notes, divulgation_affiliation=excluded.divulgation_affiliation, mention_risque=excluded.mention_risque, mention_non_affiliation=excluded.mention_non_affiliation, updated_at=excluded.updated_at;
INSERT INTO lien_parrainage (id, parrain_id, offre_id, url_parrainage, code_parrainage, quota_max, quota_utilise, date_dernier_tour, date_reinitialisation, statut, created_at) VALUES ('LP-PAR-EMMANUEL-REF-001', 'PAR-EMMANUEL', 'REF-001', 'https://ref.trade.re/1dw9h6jf', '1dw9h6jf', NULL, 0, NULL, NULL, 'actif', (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage;

-- REF-006 Qonto (actif)
INSERT INTO offre (id, nom_programme, categorie, sous_categorie, cible, pays, langue, url_parrainage, code_parrainage, description_courte, avantage_filleul, avantage_parrain, conditions, statut, priorite_affichage, tags_mcp, date_ajout, date_verification, source, notes, divulgation_affiliation, mention_risque, mention_non_affiliation, created_at, updated_at) VALUES ('REF-006', 'Qonto', 'Services entrepreneur', 'Banque professionnelle', 'Entrepreneur', 'FR / EU', 'fr', 'https://qonto.com/r/ux2pft', 'ux2pft', 'Néobanque professionnelle : compte pro, cartes, gestion des dépenses et facturation pour sociétés et indépendants.', '80 EUR + 80 EUR (deux paliers)', '80 EUR + 80 EUR (deux paliers)', 'Palier 1 : 50 EUR dépensés en carte physique + 1 paiement d''abonnement Qonto dans les 2 premiers mois → 80 EUR chacun. Palier 2 : 3 000 EUR dépensés en carte physique dans les 2 premiers mois → 80 EUR supplémentaires chacun.', 'actif', 1, 'banque pro; compte pro; entrepreneur; facturation; SASU; SARL', '2026-07-15', '2026-07-15', 'Linktree EmelGoez — extraction 15/07/2026', NULL, 'Lien de parrainage Qonto : Parrainly perçoit un avantage personnel (Thomas ou Emmanuel) si vous l''utilisez pour vous inscrire.', NULL, 'Parrainly n''est pas affilié officiellement à Qonto.', (unixepoch() * 1000), (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET nom_programme=excluded.nom_programme, categorie=excluded.categorie, sous_categorie=excluded.sous_categorie, cible=excluded.cible, pays=excluded.pays, langue=excluded.langue, url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage, description_courte=excluded.description_courte, avantage_filleul=excluded.avantage_filleul, avantage_parrain=excluded.avantage_parrain, conditions=excluded.conditions, statut=excluded.statut, priorite_affichage=excluded.priorite_affichage, tags_mcp=excluded.tags_mcp, date_ajout=excluded.date_ajout, date_verification=excluded.date_verification, source=excluded.source, notes=excluded.notes, divulgation_affiliation=excluded.divulgation_affiliation, mention_risque=excluded.mention_risque, mention_non_affiliation=excluded.mention_non_affiliation, updated_at=excluded.updated_at;
INSERT INTO lien_parrainage (id, parrain_id, offre_id, url_parrainage, code_parrainage, quota_max, quota_utilise, date_dernier_tour, date_reinitialisation, statut, created_at) VALUES ('LP-PAR-EMMANUEL-REF-006', 'PAR-EMMANUEL', 'REF-006', 'https://qonto.com/r/ux2pft', 'ux2pft', NULL, 0, NULL, NULL, 'actif', (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage;

-- REF-007 Revolut Business (actif)
INSERT INTO offre (id, nom_programme, categorie, sous_categorie, cible, pays, langue, url_parrainage, code_parrainage, description_courte, avantage_filleul, avantage_parrain, conditions, statut, priorite_affichage, tags_mcp, date_ajout, date_verification, source, notes, divulgation_affiliation, mention_risque, mention_non_affiliation, created_at, updated_at) VALUES ('REF-007', 'Revolut Business', 'Services entrepreneur', 'Banque professionnelle', 'Entrepreneur', 'FR / EU', 'fr; en', 'https://business.revolut.com/signup?promo=B2B-JUL1-26-AR-H3&ext=00dcd3ec-7f84-490f-8f4f-247f15f9e4e5&context=B2B_REFERRAL', 'B2B-JUL1-26-AR-H3', 'Compte professionnel multi-devises : paiements internationaux, cartes équipe, intégrations comptables.', '850 EUR', '850 EUR', 'Inscription via le lien, création d''un compte Revolut Business, validation des contrôles d''éligibilité (entreprise + personnelle), commande d''une carte physique, alimentation du compte, puis au moins 50 EUR d''achats (jeux et virements exclus).', 'actif', 2, 'banque pro; multi-devises; international; compte pro; entrepreneur', '2026-07-15', '2026-07-15', 'Linktree EmelGoez — extraction 15/07/2026', 'Code promo extrait du paramètre ''promo'' de l''URL — campagne datée (JUL1-26), vérifier sa validité régulièrement.', 'Lien de parrainage Revolut Business : Parrainly perçoit un avantage personnel (Thomas ou Emmanuel) si vous l''utilisez pour vous inscrire.', NULL, 'Parrainly n''est pas affilié officiellement à Revolut Business.', (unixepoch() * 1000), (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET nom_programme=excluded.nom_programme, categorie=excluded.categorie, sous_categorie=excluded.sous_categorie, cible=excluded.cible, pays=excluded.pays, langue=excluded.langue, url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage, description_courte=excluded.description_courte, avantage_filleul=excluded.avantage_filleul, avantage_parrain=excluded.avantage_parrain, conditions=excluded.conditions, statut=excluded.statut, priorite_affichage=excluded.priorite_affichage, tags_mcp=excluded.tags_mcp, date_ajout=excluded.date_ajout, date_verification=excluded.date_verification, source=excluded.source, notes=excluded.notes, divulgation_affiliation=excluded.divulgation_affiliation, mention_risque=excluded.mention_risque, mention_non_affiliation=excluded.mention_non_affiliation, updated_at=excluded.updated_at;
INSERT INTO lien_parrainage (id, parrain_id, offre_id, url_parrainage, code_parrainage, quota_max, quota_utilise, date_dernier_tour, date_reinitialisation, statut, created_at) VALUES ('LP-PAR-EMMANUEL-REF-007', 'PAR-EMMANUEL', 'REF-007', 'https://business.revolut.com/signup?promo=B2B-JUL1-26-AR-H3&ext=00dcd3ec-7f84-490f-8f4f-247f15f9e4e5&context=B2B_REFERRAL', 'B2B-JUL1-26-AR-H3', NULL, 0, NULL, NULL, 'actif', (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage;

-- REF-002 Ramify (actif)
INSERT INTO offre (id, nom_programme, categorie, sous_categorie, cible, pays, langue, url_parrainage, code_parrainage, description_courte, avantage_filleul, avantage_parrain, conditions, statut, priorite_affichage, tags_mcp, date_ajout, date_verification, source, notes, divulgation_affiliation, mention_risque, mention_non_affiliation, created_at, updated_at) VALUES ('REF-002', 'Ramify', 'Investissement', 'Plateforme d''investissement', 'Jeune actif; Entrepreneur', 'FR', 'fr', 'https://app.ramify.fr/creer-un-compte?code=JHOHSV', 'JHOHSV', 'Plateforme d''investissement française : assurance-vie, PER, private equity, SCPI, gestion pilotée.', '3 mois de frais de gestion offerts (produits à frais de gestion) OU remise de 1% du montant souscrit (produits à frais d''acquisition)', '50 EUR (1er investissement ≥ 1 000 EUR), 100 EUR (≥ 10 000 EUR) ou 250 EUR (≥ 100 000 EUR) — hors produits Cash', 'Pas de délai pour le 1er investissement du filleul ; ensuite, 30 jours pour souscrire d''autres produits comptant dans la prime.', 'actif', 1, 'assurance-vie; PER; SCPI; private equity; gestion pilotée; défiscalisation', '2026-07-15', '2026-07-15', 'Linktree EmelGoez — extraction 15/07/2026', NULL, 'Lien de parrainage Ramify : Parrainly perçoit un avantage personnel (Thomas ou Emmanuel) si vous l''utilisez pour vous inscrire.', 'Investir comporte des risques de perte en capital.', 'Parrainly n''est pas affilié officiellement à Ramify.', (unixepoch() * 1000), (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET nom_programme=excluded.nom_programme, categorie=excluded.categorie, sous_categorie=excluded.sous_categorie, cible=excluded.cible, pays=excluded.pays, langue=excluded.langue, url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage, description_courte=excluded.description_courte, avantage_filleul=excluded.avantage_filleul, avantage_parrain=excluded.avantage_parrain, conditions=excluded.conditions, statut=excluded.statut, priorite_affichage=excluded.priorite_affichage, tags_mcp=excluded.tags_mcp, date_ajout=excluded.date_ajout, date_verification=excluded.date_verification, source=excluded.source, notes=excluded.notes, divulgation_affiliation=excluded.divulgation_affiliation, mention_risque=excluded.mention_risque, mention_non_affiliation=excluded.mention_non_affiliation, updated_at=excluded.updated_at;
INSERT INTO lien_parrainage (id, parrain_id, offre_id, url_parrainage, code_parrainage, quota_max, quota_utilise, date_dernier_tour, date_reinitialisation, statut, created_at) VALUES ('LP-PAR-EMMANUEL-REF-002', 'PAR-EMMANUEL', 'REF-002', 'https://app.ramify.fr/creer-un-compte?code=JHOHSV', 'JHOHSV', NULL, 0, NULL, NULL, 'actif', (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage;

-- REF-003 Finary (actif)
INSERT INTO offre (id, nom_programme, categorie, sous_categorie, cible, pays, langue, url_parrainage, code_parrainage, description_courte, avantage_filleul, avantage_parrain, conditions, statut, priorite_affichage, tags_mcp, date_ajout, date_verification, source, notes, divulgation_affiliation, mention_risque, mention_non_affiliation, created_at, updated_at) VALUES ('REF-003', 'Finary', 'Gestion de patrimoine', 'Agrégateur patrimonial', 'Jeune actif; Entrepreneur', 'FR / EU', 'fr; en', 'https://finary.com/referral/7KGZAX', '7KGZAX', 'Suivi et analyse de l''ensemble du patrimoine (comptes, immobilier, crypto, actions) dans une seule application.', '1 mois de Premium offert', '1 mois d''abonnement supplémentaire', 'Être membre gratuit ou abonné via le site web. Abonnements souscrits via iOS/Android non éligibles (limitation technique).', 'actif', 1, 'patrimoine; agrégateur; tracking; net worth; reporting', '2026-07-15', '2026-07-15', 'Linktree EmelGoez — extraction 15/07/2026', NULL, 'Lien de parrainage Finary : Parrainly perçoit un avantage personnel (Thomas ou Emmanuel) si vous l''utilisez pour vous inscrire.', 'Investir comporte des risques de perte en capital.', 'Parrainly n''est pas affilié officiellement à Finary.', (unixepoch() * 1000), (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET nom_programme=excluded.nom_programme, categorie=excluded.categorie, sous_categorie=excluded.sous_categorie, cible=excluded.cible, pays=excluded.pays, langue=excluded.langue, url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage, description_courte=excluded.description_courte, avantage_filleul=excluded.avantage_filleul, avantage_parrain=excluded.avantage_parrain, conditions=excluded.conditions, statut=excluded.statut, priorite_affichage=excluded.priorite_affichage, tags_mcp=excluded.tags_mcp, date_ajout=excluded.date_ajout, date_verification=excluded.date_verification, source=excluded.source, notes=excluded.notes, divulgation_affiliation=excluded.divulgation_affiliation, mention_risque=excluded.mention_risque, mention_non_affiliation=excluded.mention_non_affiliation, updated_at=excluded.updated_at;
INSERT INTO lien_parrainage (id, parrain_id, offre_id, url_parrainage, code_parrainage, quota_max, quota_utilise, date_dernier_tour, date_reinitialisation, statut, created_at) VALUES ('LP-PAR-EMMANUEL-REF-003', 'PAR-EMMANUEL', 'REF-003', 'https://finary.com/referral/7KGZAX', '7KGZAX', NULL, 0, NULL, NULL, 'actif', (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage;

-- REF-004 Dougs (actif)
INSERT INTO offre (id, nom_programme, categorie, sous_categorie, cible, pays, langue, url_parrainage, code_parrainage, description_courte, avantage_filleul, avantage_parrain, conditions, statut, priorite_affichage, tags_mcp, date_ajout, date_verification, source, notes, divulgation_affiliation, mention_risque, mention_non_affiliation, created_at, updated_at) VALUES ('REF-004', 'Dougs', 'Services entrepreneur', 'Expertise comptable en ligne', 'Entrepreneur', 'FR', 'fr', 'https://www.dougs.fr?r=OWNQ93kmgD', 'OWNQ93kmgD', 'Expert-comptable en ligne 100% dématérialisé, comptabilité à partir de 49 EUR/mois. Adapté aux sociétés et indépendants.', '1 mois offert', '1 mois offert', 'Parrainage validé dès que le filleul choisit un pack.', 'actif', 2, 'comptabilité; expert-comptable; SASU; SARL; freelance; création entreprise', '2026-07-15', '2026-07-15', 'Linktree EmelGoez — extraction 15/07/2026', NULL, 'Lien de parrainage Dougs : Parrainly perçoit un avantage personnel (Thomas ou Emmanuel) si vous l''utilisez pour vous inscrire.', NULL, 'Parrainly n''est pas affilié officiellement à Dougs.', (unixepoch() * 1000), (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET nom_programme=excluded.nom_programme, categorie=excluded.categorie, sous_categorie=excluded.sous_categorie, cible=excluded.cible, pays=excluded.pays, langue=excluded.langue, url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage, description_courte=excluded.description_courte, avantage_filleul=excluded.avantage_filleul, avantage_parrain=excluded.avantage_parrain, conditions=excluded.conditions, statut=excluded.statut, priorite_affichage=excluded.priorite_affichage, tags_mcp=excluded.tags_mcp, date_ajout=excluded.date_ajout, date_verification=excluded.date_verification, source=excluded.source, notes=excluded.notes, divulgation_affiliation=excluded.divulgation_affiliation, mention_risque=excluded.mention_risque, mention_non_affiliation=excluded.mention_non_affiliation, updated_at=excluded.updated_at;
INSERT INTO lien_parrainage (id, parrain_id, offre_id, url_parrainage, code_parrainage, quota_max, quota_utilise, date_dernier_tour, date_reinitialisation, statut, created_at) VALUES ('LP-PAR-EMMANUEL-REF-004', 'PAR-EMMANUEL', 'REF-004', 'https://www.dougs.fr?r=OWNQ93kmgD', 'OWNQ93kmgD', NULL, 0, NULL, NULL, 'actif', (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage;

-- REF-008 Meria (actif)
INSERT INTO offre (id, nom_programme, categorie, sous_categorie, cible, pays, langue, url_parrainage, code_parrainage, description_courte, avantage_filleul, avantage_parrain, conditions, statut, priorite_affichage, tags_mcp, date_ajout, date_verification, source, notes, divulgation_affiliation, mention_risque, mention_non_affiliation, created_at, updated_at) VALUES ('REF-008', 'Meria', 'Crypto', 'Exchange', 'Jeune actif; Entrepreneur', 'FR / EU', 'fr', 'https://www.meria.com/r/iOTwY6Zs', 'iOTwY6Zs', 'Plateforme crypto française régulée : achat BTC/ETH, staking et lending, dépôts EUR.', 'Part de 10 USDC', 'Part de 10 USDC', 'Inscription via le lien + KYC validé, premier achat spot ≥ 100 EUR (virement ou CB), puis staking ou lending de tout ou partie. Répartition de la récompense définie par le parrain.', 'actif', 2, 'crypto; bitcoin; ethereum; staking; lending; PSAN', '2026-07-15', '2026-07-15', 'Linktree EmelGoez — extraction 15/07/2026', NULL, 'Lien de parrainage Meria : Parrainly perçoit un avantage personnel (Thomas ou Emmanuel) si vous l''utilisez pour vous inscrire.', 'Les crypto-actifs sont des actifs risqués, leur valeur peut fortement varier.', 'Parrainly n''est pas affilié officiellement à Meria.', (unixepoch() * 1000), (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET nom_programme=excluded.nom_programme, categorie=excluded.categorie, sous_categorie=excluded.sous_categorie, cible=excluded.cible, pays=excluded.pays, langue=excluded.langue, url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage, description_courte=excluded.description_courte, avantage_filleul=excluded.avantage_filleul, avantage_parrain=excluded.avantage_parrain, conditions=excluded.conditions, statut=excluded.statut, priorite_affichage=excluded.priorite_affichage, tags_mcp=excluded.tags_mcp, date_ajout=excluded.date_ajout, date_verification=excluded.date_verification, source=excluded.source, notes=excluded.notes, divulgation_affiliation=excluded.divulgation_affiliation, mention_risque=excluded.mention_risque, mention_non_affiliation=excluded.mention_non_affiliation, updated_at=excluded.updated_at;
INSERT INTO lien_parrainage (id, parrain_id, offre_id, url_parrainage, code_parrainage, quota_max, quota_utilise, date_dernier_tour, date_reinitialisation, statut, created_at) VALUES ('LP-PAR-EMMANUEL-REF-008', 'PAR-EMMANUEL', 'REF-008', 'https://www.meria.com/r/iOTwY6Zs', 'iOTwY6Zs', NULL, 0, NULL, NULL, 'actif', (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage;

-- REF-005 Kraken (actif)
INSERT INTO offre (id, nom_programme, categorie, sous_categorie, cible, pays, langue, url_parrainage, code_parrainage, description_courte, avantage_filleul, avantage_parrain, conditions, statut, priorite_affichage, tags_mcp, date_ajout, date_verification, source, notes, divulgation_affiliation, mention_risque, mention_non_affiliation, created_at, updated_at) VALUES ('REF-005', 'Kraken', 'Crypto', 'Exchange', 'Jeune actif; Entrepreneur', 'International', 'fr; en', 'https://invite.kraken.com/JDNW/ozgnzx2r', 'ozgnzx2r', 'Exchange crypto historique et régulé (BTC, ETH...) : dépôts EUR/USD/GBP, trading spot et margin.', '25 à 250 EUR (récompense aléatoire)', '25 à 250 EUR (récompense aléatoire)', 'Récompense attribuée une fois que le filleul a déposé des fonds et effectué 200 EUR de transactions.', 'actif', 1, 'crypto; bitcoin; ethereum; exchange; trading', '2026-07-15', '2026-07-15', 'Linktree EmelGoez — extraction 15/07/2026', NULL, 'Lien de parrainage Kraken : Parrainly perçoit un avantage personnel (Thomas ou Emmanuel) si vous l''utilisez pour vous inscrire.', 'Les crypto-actifs sont des actifs risqués, leur valeur peut fortement varier.', 'Parrainly n''est pas affilié officiellement à Kraken.', (unixepoch() * 1000), (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET nom_programme=excluded.nom_programme, categorie=excluded.categorie, sous_categorie=excluded.sous_categorie, cible=excluded.cible, pays=excluded.pays, langue=excluded.langue, url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage, description_courte=excluded.description_courte, avantage_filleul=excluded.avantage_filleul, avantage_parrain=excluded.avantage_parrain, conditions=excluded.conditions, statut=excluded.statut, priorite_affichage=excluded.priorite_affichage, tags_mcp=excluded.tags_mcp, date_ajout=excluded.date_ajout, date_verification=excluded.date_verification, source=excluded.source, notes=excluded.notes, divulgation_affiliation=excluded.divulgation_affiliation, mention_risque=excluded.mention_risque, mention_non_affiliation=excluded.mention_non_affiliation, updated_at=excluded.updated_at;
INSERT INTO lien_parrainage (id, parrain_id, offre_id, url_parrainage, code_parrainage, quota_max, quota_utilise, date_dernier_tour, date_reinitialisation, statut, created_at) VALUES ('LP-PAR-EMMANUEL-REF-005', 'PAR-EMMANUEL', 'REF-005', 'https://invite.kraken.com/JDNW/ozgnzx2r', 'ozgnzx2r', NULL, 0, NULL, NULL, 'actif', (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage;

-- REF-009 Spiko (actif)
INSERT INTO offre (id, nom_programme, categorie, sous_categorie, cible, pays, langue, url_parrainage, code_parrainage, description_courte, avantage_filleul, avantage_parrain, conditions, statut, priorite_affichage, tags_mcp, date_ajout, date_verification, source, notes, divulgation_affiliation, mention_risque, mention_non_affiliation, created_at, updated_at) VALUES ('REF-009', 'Spiko', 'Placement trésorerie', 'Fonds monétaires tokenisés', 'Jeune actif; Entrepreneur', 'FR / EU', 'fr; en', 'https://www.spiko.io/fr/?refer=9751F5C9BC', '9751F5C9BC', 'Placement de trésorerie (particuliers et entreprises) en fonds monétaires investis en bons du Trésor EU/US, régulé AMF. Intérêts calculés quotidiennement, fonds disponibles à tout moment.', '+0,7 point de rendement pendant 6 mois (selon campagne en cours)', 'Paliers selon dépôts du filleul sous 30 jours : 50 EUR (≥ 10 000 EUR), 100 EUR (≥ 50 000 EUR), 250 EUR (≥ 500 000 EUR), 500 EUR (≥ 1 M EUR), 1 000 EUR (≥ 3 M EUR)', 'Le filleul ouvre son compte via le lien de parrainage et dépose dans l''un des OPC dans les 30 jours calendaires suivant la validation de son compte.', 'actif', 1, 'trésorerie; trésorerie entreprise; fonds monétaire; T-Bills; compte rémunéré; cash management; AMF', '2026-07-18', '2026-07-18', 'Linktree EmelGoez — extraction 15/07/2026', 'Avantages vérifiés le 18/07/2026 (CGU parrainage Spiko + sources tierces). Le bonus filleul (+0,7 pt / 6 mois) dépend de la campagne en cours — à revérifier périodiquement.', 'Lien de parrainage Spiko : Parrainly perçoit un avantage personnel (Thomas ou Emmanuel) si vous l''utilisez pour vous inscrire.', 'Investir comporte des risques de perte en capital.', 'Parrainly n''est pas affilié officiellement à Spiko.', (unixepoch() * 1000), (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET nom_programme=excluded.nom_programme, categorie=excluded.categorie, sous_categorie=excluded.sous_categorie, cible=excluded.cible, pays=excluded.pays, langue=excluded.langue, url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage, description_courte=excluded.description_courte, avantage_filleul=excluded.avantage_filleul, avantage_parrain=excluded.avantage_parrain, conditions=excluded.conditions, statut=excluded.statut, priorite_affichage=excluded.priorite_affichage, tags_mcp=excluded.tags_mcp, date_ajout=excluded.date_ajout, date_verification=excluded.date_verification, source=excluded.source, notes=excluded.notes, divulgation_affiliation=excluded.divulgation_affiliation, mention_risque=excluded.mention_risque, mention_non_affiliation=excluded.mention_non_affiliation, updated_at=excluded.updated_at;
INSERT INTO lien_parrainage (id, parrain_id, offre_id, url_parrainage, code_parrainage, quota_max, quota_utilise, date_dernier_tour, date_reinitialisation, statut, created_at) VALUES ('LP-PAR-EMMANUEL-REF-009', 'PAR-EMMANUEL', 'REF-009', 'https://www.spiko.io/fr/?refer=9751F5C9BC', '9751F5C9BC', NULL, 0, NULL, NULL, 'actif', (unixepoch() * 1000))
ON CONFLICT(id) DO UPDATE SET url_parrainage=excluded.url_parrainage, code_parrainage=excluded.code_parrainage;
